// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TechStore.DataAccess.Data;

#nullable disable

namespace TechStore.DataAccess.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
    [Migration("20241202143911_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 12,
                            Name = "LENOVO"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 5,
                            Name = "ASUS"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "ACER"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "DELL"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 6,
                            Name = "MSI"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 2,
                            Name = "HP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
